### PR TITLE
Fix push test

### PR DESCRIPTION
**Pull request by b1zzu**
Downgrade to Cordova 8 for this reason: https://github.com/apache/cordova-android/issues/801

### CODE REVIEW

**Comment by b1zzu** [comment]
All tests are passing: https://mobile-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/blue/organizations/jenkins/test-aerogear-integration-tests/detail/fix-push-test/16/pipeline

**Comment by jhellar** [comment]
From the linked issue, it seems it is not an intermittent issue, right? Do you know why it works fine in our showcase app with cordova 9?

**Comment by b1zzu** [comment]
I think that in the showcase works because of ionic, when ionic is present is ionic to prepare the project, but I'm not sure

**Comment by b1zzu** [comment]
@jhellar do you want to understand better why this happened?

**Comment by b1zzu** [comment]
@jhellar I've found and alternative solution wdyt?

**Pull request merged**
